sudo: required
services:
  - docker

before_install:
  - docker build -t bharath6692/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bharath6692/react-test npm run test

after_success:
  - docker build -t bharath6692/multi-client ./client
  - docker build -t bharath6692/multi-nginx ./nginx
  - docker build -t bharath6692/multi-server ./server
  - docker build -t bharath6692/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bharath6692/multi-client
  - docker push bharath6692/multi-nginx
  - docker push bharath6692/multi-server
  - docker push bharath6692/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-335968110528
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: 
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY